### ISSUE TITLE
Category and tags doesn't show on production? 

### ISSUE THREAD

**Issue by erdemoflaz** [francesco-es/jekyll-tag-categories-link#1]
why categories and tags pages doesn't show on production? 

blog: https://erdemoflaz.com/

**Comment by phoinixi** [comment]
Hi, thanks for bringing this up, which version of jekyll are you using?

**Comment by erdemoflaz** [comment]
3.6.2

**Comment by erdemoflaz** [comment]
hi bro, i solved my issue.

The **categories** and **tags** folder that is generated under the **_site** folder are exported to the **main directory**
